version: '3'

services:
    database:
        image: 'postgres:latest'
        ports:
            - '${POSTGRES_PORT}:${POSTGRES_PORT}'
        restart: always
        environment:
            POSTGRES_USER: '${POSTGRES_USER}'
            POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
            POSTGRES_DB: '${POSTGRES_DB}'

    next:
        build: .
        ports:
            - '${APP_PORT}:${APP_PORT}'
        depends_on:
            - database
