name: Main Pipeline
on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]
jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: cypress/browsers:node16.14.0-chrome99-ff97
            options: --user 1001

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Install dependencies
              uses: cypress-io/github-action@v4
              with:
                  runTests: false

            - name: Format Check
              run: yarn format

            - name: Lint Check
              run: yarn lint

            - name: Type Check
              run: yarn check-types

            - name: Run unit tests
              run: yarn test:ci

            # Run Cypress tests
            - name: Run e2e tests
              uses: cypress-io/github-action@v4
              with:
                  browser: chrome
                  wait-on: 'http://localhost:3000'
                  build: yarn build
                  start: yarn start

    deploy:
        runs-on: ubuntu-latest
        env:
            VERCEL_TOKEN: 'UKjC9XeNBVFZYXPUfMaLYzmY'
            VERCEL_ORG_ID: 'mEtXaNaX3NUKvp5zuScr7eKp'
            VERCEL_PROJECT_ID: 'prj_oLfIavnJ6N9GCrNeuTm03g8tQ6By'
        needs: [build]
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: '16.x'

            - name: Deploy to Vercel
              run: npx vercel --token ${VERCEL_TOKEN} --prod
